services:
  - type: web
    name: translation-microservice
    env: python
    buildCommand: pip install -r translation_microservice/requirements.txt
    startCommand: uvicorn translation_microservice.main:app --host=0.0.0.0 --port=10000
    pythonVersion: 3.11
    plan: free
